services:
  db:
    container_name: postgresql
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
