services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - '${HOST_PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
      GOOGLE_MAIL_PASS: ${GOOGLE_MAIL_PASS}
    restart: always
    volumes:
      - ./src/logs:/app/src/logs
