name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          timeout: 60m
          command_timeout: 30m
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/2-Docthru-team1-BE

            # 메모리 정리
            sudo sync && sudo sysctl -w vm.drop_caches=3
            free -m

            # 이전 프로세스 정리 (더 안전한 방식)
            if [ -f ./server.pid ]; then
              old_pid=$(cat ./server.pid)
              if ps -p $old_pid > /dev/null; then
                echo "종료 중인 프로세스: $old_pid"
                kill -15 $old_pid
                sleep 5
                if ps -p $old_pid > /dev/null; then
                  echo "프로세스 강제 종료: $old_pid"
                  kill -9 $old_pid
                fi
              fi
              rm -f ./server.pid
            fi

            # 남은 프로세스 정리
            for pid in $(pgrep -f "tsx.*src/app.ts"); do
              echo "추가 프로세스 종료: $pid"
              kill -15 $pid
            done
            sleep 5

            # Git 작업 전 상태 확인
            echo "현재 메모리 상태:"
            free -m
            echo "현재 실행 중인 Node 프로세스:"
            ps aux | grep node

            # Git 작업
            git fetch origin main
            git reset --hard origin/main

            # 의존성 설치
            rm -rf node_modules
            npm cache clean --force
            NODE_OPTIONS="--max-old-space-size=384" npm install

            # 환경 설정
            source /etc/profile.d/HanCook-env.sh
            export NODE_ENV=production
            export DATABASE_URL="$DATABASE_URL"

            # Prisma 작업
            npx prisma generate
            npx prisma migrate deploy
            npx prisma db seed

            # 서버 실행
            echo "" > app.log
            sudo touch /etc/authbind/byport/80 /etc/authbind/byport/443
            sudo chmod 777 /etc/authbind/byport/80 /etc/authbind/byport/443

            NODE_OPTIONS="--max-old-space-size=384" nohup authbind --deep npm run dev > app.log 2>&1 &
            pid=$!
            echo $pid > ./server.pid

            # 프로세스 확인
            sleep 15
            if ps -p $pid > /dev/null; then
              echo "서버 시작 성공 (PID: $pid)"
              free -m
              ps aux | grep node
              exit 0
            else
              echo "서버 시작 실패. 로그:"
              tail -n 50 app.log
              exit 1
            fi
