name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/2-Docthru-team1-BE
            git fetch origin main
            git reset --hard origin/main

            # 환경 변수 파일 로드
            source /etc/profile.d/HanCook-env.sh

            # 기존 프로세스 종료
            pkill -f "node dist/src/app.js" || true

            npm install
            export DATABASE_URL="$DATABASE_URL" && npx prisma migrate dev
            npx tsc

            # authbind 설정
            sudo touch /etc/authbind/byport/80
            sudo touch /etc/authbind/byport/443
            sudo chmod 777 /etc/authbind/byport/80
            sudo chmod 777 /etc/authbind/byport/443

            # nohup으로 서버 시작
            nohup authbind --deep node dist/src/app.js > app.log 2>&1 &

            # 프로세스 상태 확인
            ps aux | grep "node dist/src/app.js"
            echo "Deployment completed. Check app.log for details."
