name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          timeout: 60m
          command_timeout: 30m
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/2-Docthru-team1-BE

            # 기존 프로세스 강제 종료
            if [ -f ./server.pid ]; then
              kill -9 $(cat ./server.pid) 2>/dev/null || true
              rm -f ./server.pid
            fi
            pkill -9 -f "tsx.*src/app.ts" 2>/dev/null || true
            sleep 10  # 프로세스 완전 종료 대기 시간 증가

            # Git 작업
            git fetch origin main
            git reset --hard origin/main

            # 환경 변수 설정
            source /etc/profile.d/HanCook-env.sh
            export NODE_ENV=production
            export DATABASE_URL="$DATABASE_URL"

            # 의존성 설치 및 DB 마이그레이션
            npm install
            npx prisma migrate dev

            # 서버 시작 준비
            sudo touch /etc/authbind/byport/80 /etc/authbind/byport/443
            sudo chmod 777 /etc/authbind/byport/80 /etc/authbind/byport/443
            echo "" > app.log

            # 서버 실행
            nohup authbind --deep npm run dev > app.log 2>&1 &
            echo $! > ./server.pid

            # 프로세스 확인 (타임아웃 증가)
            for i in {1..30}; do
              if ps -p $(cat ./server.pid) > /dev/null; then
                echo "서버가 성공적으로 시작되었습니다. PID: $(cat ./server.pid)"
                exit 0
              fi
              echo "서버 시작 대기 중... ($i/30)"
              sleep 2
            done

            echo "서버 시작 실패. 로그:"
            tail -n 50 app.log
            exit 1
