name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          timeout: 60m
          command_timeout: 30m
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/2-Docthru-team1-BE

            # 시스템 메모리 상태 확인
            free -m

            # 기존 프로세스 정리
            if [ -f ./server.pid ]; then
              pid=$(cat ./server.pid)
              if ps -p $pid > /dev/null; then
                echo "종료할 프로세스: $pid"
                kill -15 $pid
                sleep 5
                if ps -p $pid > /dev/null; then
                  echo "강제 종료: $pid"
                  kill -9 $pid
                fi
              fi
              rm -f ./server.pid
            fi

            # Node 프로세스 정리
            pkill -f "tsx.*src/app.ts" || true
            sleep 5

            # Git 작업
            git fetch origin main
            git reset --hard origin/main

            # Node 캐시 정리
            npm cache clean --force
            rm -rf node_modules

            # 의존성 설치 및 DB 마이그레이션
            npm install
            source /etc/profile.d/HanCook-env.sh
            export NODE_ENV=production
            export DATABASE_URL="$DATABASE_URL"
            npx prisma generate
            npx prisma migrate dev

            # 서버 실행
            echo "" > app.log
            sudo touch /etc/authbind/byport/80 /etc/authbind/byport/443
            sudo chmod 777 /etc/authbind/byport/80 /etc/authbind/byport/443

            NODE_OPTIONS="--max-old-space-size=2048" nohup authbind --deep npm run dev > app.log 2>&1 &
            echo $! > ./server.pid

            # 프로세스 상태 확인
            sleep 15
            if ps -p $(cat ./server.pid) > /dev/null; then
              echo "서버 시작 성공 (PID: $(cat ./server.pid))"
              exit 0
            else
              echo "서버 시작 실패. 로그:"
              tail -n 50 app.log
              exit 1
            fi
